/*
 * 	 LCD5x8.c
 *
 * Font generated by ATNEL - SFG (part of PixelFactory)
 * http://atnel.pl/pixel-factory.html
 * (C) 2015 by Atnel. Mirosław Kardaś
 */
#include "../../../libs/SW_GRAPHICS/fonts_common.h"

//  Font data for LCD5x8


// Character bitmaps for LCD5x8

const uint8_t PlayIcons8x8_fixeBitmaps[]  = {
	0x04,0x0C,0x1C,0x3C,0x3C,0x1C,0x0C,0x04,      // char 0  (48)
	0x20,0x30,0x38,0x3C,0x3C,0x38,0x30,0x20,      // char 1  (49)
	0x18,0x3C,0x7E,0x00,0x00,0x7E,0x3C,0x18,      // char 2  (50)
	0x18,0x3C,0x7E,0x00,0x00,0x00,0x00,0x00,      // char 3  (51)
	0x00,0x00,0x00,0x00,0x00,0x7E,0x3C,0x18,      // char 4  (52)
	0x18,0x66,0x42,0x99,0x99,0x42,0x66,0x18,      // char 5  (53)
	0x18,0x66,0x42,0x81,0x81,0x42,0x66,0x18,      // char 6  (54)
	0x11,0x33,0x77,0xFF,0xFF,0x77,0x33,0x11,      // char 7  (55)
	0x88,0xCC,0xEE,0xFF,0xFF,0xEE,0xCC,0x88,      // char 8  (56)
	0x00,0x66,0x66,0x66,0x66,0x66,0x66,0x00,      // char 9  (57)
};

// descriptors
const FONT_CHAR_INFO PlayIcons8x8_fixeDescriptors[]  = {
	{ 8,0 },	// 0  (48)
	{ 8,8 },	// 1  (49)
	{ 8,16 },	// 2  (50)
	{ 8,24 },	// 3  (51)
	{ 8,32 },	// 4  (52)
	{ 8,40 },	// 5  (53)
	{ 8,48 },	// 6  (54)
	{ 8,56 },	// 7  (55)
	{ 8,64 },	// 8  (56)
	{ 8,72 },	// 9  (57)
};

// Font information
const FONT_INFO PlayIcons8x8_fixeInfo  = {
	8,		// Character height
	'0',	// Start character
	0,		// number of pixels of interspace between characters
	2,		// number of pixels of space character
	PlayIcons8x8_fixeDescriptors,	// number of pixels of space character
	PlayIcons8x8_fixeBitmaps,	// number of pixels of space character
	sizeof(PlayIcons8x8_fixeDescriptors) / sizeof(PlayIcons8x8_fixeDescriptors[0]),
};
