/*
 * 	 LCD5x8.c
 *
 * Font generated by ATNEL - SFG (part of PixelFactory)
 * http://atnel.pl/pixel-factory.html
 * (C) 2015 by Atnel. Mirosław Kardaś
 */
#include "../../../libs/SW_GRAPHICS/fonts_common.h"

//  Font data for LCD5x8


// Character bitmaps for LCD5x8

const uint8_t PlayIcons8x8_tightBitmaps[]  = {
	0x10,0x30,0x70,0xF0,0xF0,0x70,0x30,0x10,      // char 0  (48)
	0x80,0xC0,0xE0,0xF0,0xF0,0xE0,0xC0,0x80,      // char 1  (49)
	0x30,0x78,0xFC,0x00,0x00,0xFC,0x78,0x30,      // char 2  (50)
	0x30,0x78,0xFC,0x00,0x00,0x00,0x00,0x00,      // char 3  (51)
	0x00,0x00,0x00,0x00,0x00,0xFC,0x78,0x30,      // char 4  (52)
	0x18,0x7E,0x7E,0xFF,0xFF,0x7E,0x7E,0x18,      // char 5  (53)
	0x18,0x66,0x42,0x81,0x81,0x42,0x66,0x18,      // char 6  (54)
	0x11,0x33,0x77,0xFF,0xFF,0x77,0x33,0x11,      // char 7  (55)
	0x88,0xCC,0xEE,0xFF,0xFF,0xEE,0xCC,0x88,      // char 8  (56)
	0x00,0xCC,0xCC,0xCC,0xCC,0xCC,0xCC,0x00,      // char 9  (57)
	0x00,0x20,0x40,0xF8,0x40,0x20,0x00,0x00,      // char :  (58)
};

// descriptors
const FONT_CHAR_INFO PlayIcons8x8_tightDescriptors[]  = {
	{ 4,0 },	// 0  (48)
	{ 4,8 },	// 1  (49)
	{ 6,16 },	// 2  (50)
	{ 6,24 },	// 3  (51)
	{ 6,32 },	// 4  (52)
	{ 8,40 },	// 5  (53)
	{ 8,48 },	// 6  (54)
	{ 8,56 },	// 7  (55)
	{ 8,64 },	// 8  (56)
	{ 6,72 },	// 9  (57)
	{ 5,80 },	// :  (58)
};

// Font information
const FONT_INFO PlayIcons8x8_tightInfo  = {
	8,		// Character height
	'0',	// Start character
	1,		// number of pixels of interspace between characters
	2,		// number of pixels of space character
	PlayIcons8x8_tightDescriptors,	// number of pixels of space character
	PlayIcons8x8_tightBitmaps,	// number of pixels of space character
	sizeof(PlayIcons8x8_tightDescriptors) / sizeof(PlayIcons8x8_tightDescriptors[0]),
};
